version: '3'

services:
  menu-ocr-notifier:
    build: .
    ports:
      - '3000:3890'
    restart: unless-stopped
    environment:
      - PORT=3890
      - NODE_ENV=production
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
